name: 'lockfile lint'
description: 'Check a package-lock or yarn.lock file for violations'
inputs:
  lockfilePath:
    description: 'Path to the lockfile to lint'
    default: 'package-lock.json'
  schemes:
    description: 'URL schemes to allow in addition to http and https'
  hosts:
    description: 'Whitelisted registry hosts'
runs:
  using: 'node12'
  main: 'dist/index.js'
