name: 'lockfile lint'
description: 'Check a package-lock or yarn.lock file for violations'
inputs:
  lockfilePath:
    description: 'Path to the lockfile to lint'
  schemes:
    description: 'URL schemes to allow in addition to http and https'
runs:
  using: 'node12'
  main: 'src/index.js'
