on: [push, pull_request]

jobs:
  main:
    runs-on: ubuntu-latest
    name: lockfile lint
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - run: npm ci
    - name: Lint that lockfile!
      uses: ./
